// Generated by scripts/generate-contract-artifacts.py. Do not edit.
// Source: api/contracts/{capabilities,device,math,accessibility}.json

/** A stable capability availability entry. */
interface CapabilityEntry {
  readonly available: boolean;
}

/** One element exposed to screen readers by sys.accessibility.update(). */
interface AccessibilityNode {
  /** Stable id, returned with the actions on this node. */
  id: string;
  role: "button" | "checkbox" | "radio" | "switch" | "slider" | "textbox" | "list" | "listitem" | "heading" | "text" | "combobox" | "option" | "tab" | "image" | "group" | "link";
  /** What a screen reader announces. */
  label: string;
  /** Text of fields, or a readable slider value. */
  value?: string;
  /** Bounds in physical canvas pixels. */
  x: number;
  y: number;
  width: number;
  height: number;
  checked?: boolean;
  selected?: boolean;
  focused?: boolean;
  disabled?: boolean;
  expanded?: boolean;
  /** Sliders: range and current value. */
  min?: number;
  max?: number;
  rangeValue?: number;
}

/** An action requested through assistive technology. */
interface AccessibilityAction {
  readonly id: string;
  readonly action: "press" | "focus" | "increment" | "decrement" | "setValue";
  /** New text for setValue. */
  readonly value: string;
}

/** System preferences reported by sys.device.getPreferences(). */
interface DevicePreferences {
  /** The system uses a dark appearance. */
  readonly darkMode: boolean;
  /** The user asked for less motion. */
  readonly reducedMotion: boolean;
  /** The user asked for more contrast. */
  readonly highContrast: boolean;
  /** Text size multiplier chosen by the user (1 = default). */
  readonly fontScale: number;
  /** Insets, in physical pixels, to keep free of content (notches, system bars). */
  readonly safeArea: { readonly top: number; readonly right: number; readonly bottom: number; readonly left: number };
  /** Height, in physical pixels from the bottom, covered by the on-screen keyboard; 0 when hidden or on desktop. */
  readonly keyboardInset: number;
}

/** Stable per-feature availability probes for the current process and platform. */
interface SysCapabilities {
  /** ONNX Runtime neural inference availability. */
  readonly neural: CapabilityEntry;
  /** Local GGUF inference through the optional llama.cpp subsystem. */
  readonly llamacpp: CapabilityEntry;
  /** Local MIDI and RTP-MIDI availability. */
  readonly midi: CapabilityEntry;
  /** Raw UDP datagram availability. */
  readonly udp: CapabilityEntry;
  /** HTTP fetch availability. */
  readonly http: CapabilityEntry;
  /** Accelerometer and compass availability. */
  readonly sensors: CapabilityEntry;
}

/** Device-level controls owned by the current application runtime. */
interface SysDevice {
  /** Request that the screen stays on, or release this application's request. Returns false when the platform cannot apply the change. */
  keepScreenOn(enabled: boolean): boolean;
  /** Copy UTF-8 text to the system clipboard. Returns false when the platform refuses. On the web, the browser may require a recent user gesture. */
  setClipboardText(text: string): boolean;
  /** Read the clipboard text, or null when it holds none. On the web, browsers only expose the clipboard asynchronously, so this returns the last text copied, cut, or pasted on the page. */
  getClipboardText(): string | null;
  /** Play haptic feedback (default "light"). Returns false where the device has no haptics (desktop). Throws RangeError on an unknown kind. */
  haptic(kind?: "light" | "medium" | "heavy" | "selection" | "success" | "warning" | "error"): boolean;
  /** Read the user's system preferences: dark mode, reduced motion, high contrast, text scale, safe-area insets, and the on-screen keyboard's height, in physical pixels. Cheap to call every frame. */
  getPreferences(): DevicePreferences;
  /** Set the mouse cursor shape using CSS cursor names (default "default"). Returns false where there is no mouse cursor. Throws RangeError on an unknown name. */
  setCursor(name?: "default" | "text" | "pointer" | "grab" | "grabbing" | "move" | "ew-resize" | "ns-resize" | "nwse-resize" | "nesw-resize" | "not-allowed" | "wait" | "crosshair" | "none"): boolean;
}

/** In-place 3D math helpers. Matrices, vectors, and quaternions use caller-owned Float32Array storage; mat4 values are column-major. */
interface SysMath {
  mat4Identity(out: Float32Array): void;
  mat4Multiply(out: Float32Array, a: Float32Array, b: Float32Array): void;
  mat4Perspective(out: Float32Array, fovy: number, aspect: number, near: number, far: number): void;
  mat4Ortho(out: Float32Array, left: number, right: number, bottom: number, top: number, near: number, far: number): void;
  mat4LookAt(out: Float32Array, eye: Float32Array, target: Float32Array, up: Float32Array): void;
  mat4Translate(out: Float32Array, a: Float32Array, translation: Float32Array): void;
  mat4RotateX(out: Float32Array, a: Float32Array, angle: number): void;
  mat4RotateY(out: Float32Array, a: Float32Array, angle: number): void;
  mat4RotateZ(out: Float32Array, a: Float32Array, angle: number): void;
  mat4Scale(out: Float32Array, a: Float32Array, scale: Float32Array): void;
  /** Returns true when the matrix is invertible. */
  mat4Invert(out: Float32Array, a: Float32Array): boolean;
  mat4Transpose(out: Float32Array, a: Float32Array): void;
  vec3Add(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Sub(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Scale(out: Float32Array, a: Float32Array, scale: number): void;
  vec3Normalize(out: Float32Array, a: Float32Array): void;
  vec3Cross(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Dot(a: Float32Array, b: Float32Array): number;
  vec3Length(a: Float32Array): number;
  /** Transforms a vec3 as (x, y, z, 1) and applies perspective division. */
  vec3TransformMat4(out: Float32Array, value: Float32Array, matrix: Float32Array): void;
  /** Normalizes count tightly packed vec3 values in one native call. */
  vec3NormalizeMany(out: Float32Array, values: Float32Array, count: number): void;
  /** Transforms count tightly packed vec3 values by one matrix in one native call. */
  vec3TransformMat4Many(out: Float32Array, values: Float32Array, matrix: Float32Array, count: number): void;
  quatFromAxisAngle(out: Float32Array, axis: Float32Array, angle: number): void;
  quatMultiply(out: Float32Array, a: Float32Array, b: Float32Array): void;
  quatSlerp(out: Float32Array, a: Float32Array, b: Float32Array, t: number): void;
  quatToMat4(out: Float32Array, value: Float32Array): void;
}

/** Expose what the app draws to screen readers: publish a flat list of nodes every frame they change, and apply the actions users perform through assistive technology. */
interface SysAccessibility {
  /** Whether this platform exposes accessibility nodes to assistive technology (web, Android, and macOS; not Windows or Linux yet). */
  isAvailable(): boolean;
  /** Whether a screen reader or other assistive service probably runs (always true on the web, where browsers do not tell). Apps may skip building the tree when false. */
  isActive(): boolean;
  /** Replace the published tree (at most 512 nodes, in reading order; bounds in physical canvas pixels). Cheap when nothing changed. WebAssembly passes a JSON array of the same objects. */
  update(nodes: AccessibilityNode[]): boolean;
  /** Return and clear the actions requested through assistive technology since the last call: press, focus, increment, decrement, or setValue (with `value`). WebAssembly receives them as a JSON array. */
  takeActions(): AccessibilityAction[];
}
