// Generated by scripts/generate-contract-artifacts.py. Do not edit.
// Source: api/contracts/{capabilities,device,math}.json

/** A stable capability availability entry. */
interface CapabilityEntry {
  readonly available: boolean;
}

/** Stable per-feature availability probes for the current process and platform. */
interface SysCapabilities {
  /** ONNX Runtime neural inference availability. */
  readonly neural: CapabilityEntry;
  /** Local GGUF inference through the optional llama.cpp subsystem. */
  readonly llamacpp: CapabilityEntry;
  /** Local MIDI and RTP-MIDI availability. */
  readonly midi: CapabilityEntry;
  /** Raw UDP datagram availability. */
  readonly udp: CapabilityEntry;
  /** HTTP fetch availability. */
  readonly http: CapabilityEntry;
  /** Accelerometer and compass availability. */
  readonly sensors: CapabilityEntry;
}

/** Device-level controls owned by the current application runtime. */
interface SysDevice {
  /** Request that the screen stays on, or release this application's request. Returns false when the platform cannot apply the change. */
  keepScreenOn(enabled: boolean): boolean;
}

/** In-place 3D math helpers. Matrices, vectors, and quaternions use caller-owned Float32Array storage; mat4 values are column-major. */
interface SysMath {
  mat4Identity(out: Float32Array): void;
  mat4Multiply(out: Float32Array, a: Float32Array, b: Float32Array): void;
  mat4Perspective(out: Float32Array, fovy: number, aspect: number, near: number, far: number): void;
  mat4Ortho(out: Float32Array, left: number, right: number, bottom: number, top: number, near: number, far: number): void;
  mat4LookAt(out: Float32Array, eye: Float32Array, target: Float32Array, up: Float32Array): void;
  mat4Translate(out: Float32Array, a: Float32Array, translation: Float32Array): void;
  mat4RotateX(out: Float32Array, a: Float32Array, angle: number): void;
  mat4RotateY(out: Float32Array, a: Float32Array, angle: number): void;
  mat4RotateZ(out: Float32Array, a: Float32Array, angle: number): void;
  mat4Scale(out: Float32Array, a: Float32Array, scale: Float32Array): void;
  /** Returns true when the matrix is invertible. */
  mat4Invert(out: Float32Array, a: Float32Array): boolean;
  mat4Transpose(out: Float32Array, a: Float32Array): void;
  vec3Add(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Sub(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Scale(out: Float32Array, a: Float32Array, scale: number): void;
  vec3Normalize(out: Float32Array, a: Float32Array): void;
  vec3Cross(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Dot(a: Float32Array, b: Float32Array): number;
  vec3Length(a: Float32Array): number;
  /** Transforms a vec3 as (x, y, z, 1) and applies perspective division. */
  vec3TransformMat4(out: Float32Array, value: Float32Array, matrix: Float32Array): void;
  /** Normalizes count tightly packed vec3 values in one native call. */
  vec3NormalizeMany(out: Float32Array, values: Float32Array, count: number): void;
  /** Transforms count tightly packed vec3 values by one matrix in one native call. */
  vec3TransformMat4Many(out: Float32Array, values: Float32Array, matrix: Float32Array, count: number): void;
  quatFromAxisAngle(out: Float32Array, axis: Float32Array, angle: number): void;
  quatMultiply(out: Float32Array, a: Float32Array, b: Float32Array): void;
  quatSlerp(out: Float32Array, a: Float32Array, b: Float32Array, t: number): void;
  quatToMat4(out: Float32Array, value: Float32Array): void;
}
