if(NOT DEFINED BUDO OR NOT DEFINED TEST_ROOT OR NOT DEFINED TEMPLATE)
    message(FATAL_ERROR "BUDO, TEST_ROOT, and TEMPLATE are required")
endif()

file(REMOVE_RECURSE "${TEST_ROOT}")
set(command "${BUDO}" init "${TEST_ROOT}" --language c)
if(TEMPLATE STREQUAL "gpu")
    list(APPEND command --template gpu)
endif()
execute_process(
    COMMAND ${command}
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Native init failed (${result}):\n${output}\n${error}")
endif()
foreach(path main.c budo-native.json .gitignore .vscode/settings.json README.md)
    if(NOT EXISTS "${TEST_ROOT}/${path}")
        message(FATAL_ERROR "Native init did not create ${path}")
    endif()
endforeach()
foreach(path main.js main.ts main.lua main.wat main.wasm)
    if(EXISTS "${TEST_ROOT}/${path}")
        message(FATAL_ERROR "Native init leaked managed entrypoint ${path}")
    endif()
endforeach()
file(READ "${TEST_ROOT}/main.c" source)
if(source MATCHES "(^|\n)[ \t]*(int|void)[ \t]+main[ \t\r\n]*\\(")
    message(FATAL_ERROR "Native starter defines the process main function")
endif()
string(REGEX MATCHALL "budo_get_application[ \t\r\n]*\\(" descriptors "${source}")
list(LENGTH descriptors descriptor_count)
if(NOT descriptor_count EQUAL 1)
    message(FATAL_ERROR "Native starter must define exactly one descriptor")
endif()
if(TEMPLATE STREQUAL "gpu" AND NOT source MATCHES "budo_shader_program_create")
    message(FATAL_ERROR "GPU starter does not use GPU resources")
endif()
if(NOT error MATCHES "trusted, unsandboxed code")
    message(FATAL_ERROR "Native init did not print its trust warning")
endif()
if(NOT output MATCHES "budo compile" OR NOT output MATCHES "android-apk")
    message(FATAL_ERROR "Native init did not print next-step commands")
endif()
