if(NOT EXISTS "${BUILD_DIR}/budo-native-build.json")
    message(FATAL_ERROR "Native build provenance is missing")
endif()
file(READ "${BUILD_DIR}/budo-native-build.json" provenance)
if(NOT provenance MATCHES "\"schema_version\": 2")
    message(FATAL_ERROR "Native build provenance schema is not version 2")
endif()
if(NOT provenance MATCHES "\"status\": \"hit\"")
    message(FATAL_ERROR "Second build did not use the native build cache")
endif()
if(NOT provenance MATCHES "\"build_key\": \"[0-9a-f]+\"")
    message(FATAL_ERROR "Native build provenance has no content key")
endif()
if(NOT provenance MATCHES "\"output_digest\": \"[0-9a-f]+\"")
    message(FATAL_ERROR "Native build provenance has no output digest")
endif()
