if(NOT EXISTS "${BUILD_DIR}/build/bin/${OUTPUT_NAME}${EXECUTABLE_SUFFIX}")
    message(FATAL_ERROR "Native compile output is missing")
endif()
if(NOT EXISTS "${BUILD_DIR}/build/compile_commands.json")
    message(FATAL_ERROR "Native compile commands are missing")
endif()
if(NOT EXISTS "${BUILD_DIR}/budo-native-project.json")
    message(FATAL_ERROR "Normalized native project model is missing")
endif()
if(NOT EXISTS "${BUILD_DIR}/budo-native-build.json")
    message(FATAL_ERROR "Native build provenance is missing")
endif()
file(READ "${BUILD_DIR}/budo-native-build.json" provenance)
if(NOT provenance MATCHES "\"schema_version\": 2")
    message(FATAL_ERROR "Native build provenance schema is not version 2")
endif()
if(NOT provenance MATCHES "\"compiler\"")
    message(FATAL_ERROR "Native build provenance has no compiler identity")
endif()
if(NOT provenance MATCHES "\"sdk_version\"")
    message(FATAL_ERROR "Native build provenance has no SDK identity")
endif()
if(NOT provenance MATCHES "\"build_key\": \"[0-9a-f]+\"")
    message(FATAL_ERROR "Native build provenance has no content key")
endif()
if(NOT provenance MATCHES "\"inputs\"")
    message(FATAL_ERROR "Native build provenance has no component identities")
endif()
if(NOT provenance MATCHES "\"output_digest\": \"[0-9a-f]+\"")
    message(FATAL_ERROR "Native build provenance has no output digest")
endif()
if(NOT provenance MATCHES "\"build_type\": \"(Debug|Release|RelWithDebInfo)\"")
    message(FATAL_ERROR "Native build provenance has no selected configuration")
endif()
if(NOT provenance MATCHES "\"sanitizers\": \"")
    message(FATAL_ERROR "Native build provenance has no sanitizer identity")
endif()
if(DEFINED REQUIRED_ASSETS)
    foreach(asset IN LISTS REQUIRED_ASSETS)
        if(NOT EXISTS "${BUILD_DIR}/build/bin/${asset}")
            message(FATAL_ERROR "Required native asset is missing: ${asset}")
        endif()
    endforeach()
endif()
