// =============================================================================
// Budo Runtime — TypeScript Declarations
// =============================================================================
//
// Auto-generated by scripts/generate-types.sh from JS bindings and API contracts.
// Do not edit manually — run `make generate-types` to regenerate.
//
// Usage: place this file (or a symlink) in your project and include it from a
// tsconfig.json / jsconfig.json. Budo is not a DOM or Node runtime, so keep the
// ambient environment explicit:
//
//   {
//     "compilerOptions": { "lib": ["ES2020"], "types": [] },
//     "include": ["**/*.js", "budo.d.ts"]
//   }
//

// -- Color types --------------------------------------------------------------

/**
 * A color value accepted by canvas drawing functions.
 * - Hex string: `"#RRGGBB"` or `"#RRGGBBAA"`
 * - Numeric ARGB: `0xAARRGGBB`
 */
type Color = string | number;

// -- Input types --------------------------------------------------------------

interface Pointer {
  id: number;
  x: number;
  y: number;
  dx: number;
  dy: number;
  down: boolean;
  pressed: boolean;
  type: "mouse" | "touch";
}

interface Mouse {
  x: number;
  y: number;
  dx: number;
  dy: number;
  wheelX: number;
  wheelY: number;
  left: boolean;
  middle: boolean;
  right: boolean;
  leftPressed: boolean;
  rightPressed: boolean;
}

interface Keyboard {
  shift: boolean;
  ctrl: boolean;
  alt: boolean;
  meta: boolean;
}

interface TextInputEdit {
    text: string;
    selectionStart: number;
    selectionEnd: number;
}

interface TextInputComposition {
    active: boolean;
    changed: boolean;
    text: string;
    selectionStart: number;
    selectionEnd: number;
}

interface TextInputOptions {
    text: string;
    selectionStart: number;
    selectionEnd: number;
    multiline?: boolean;
    caret?: { x: number; y: number; width: number; height: number };
}

interface InputState {
  pointer: Pointer;
  pointers: Pointer[];
  mouse: Mouse;
  keyboard: Keyboard;
    /** Layout-aware UTF-8 text committed since the previous frame. */
    text: string;
    textEdit: TextInputEdit | null;
    composition: TextInputComposition;
    textInputActive: boolean;
  deltaTime: number;
  totalTime: number;
  frameCount: number;
  focused: boolean;
}

// -- MIDI message type --------------------------------------------------------

interface MidiMessage {
    status: number;
    data1: number;
    data2: number;
    /** Native receive/event timestamp in microseconds from a monotonic clock, or 0 when unavailable. */
    timestamp: number;
    type: number;
    channel: number;
    /** SysEx bytes for system-exclusive messages. */
    data?: number[];
    /** True when the message was received from an RTP-MIDI network session. */
    network?: boolean;
}

// -- MIDI device info ---------------------------------------------------------

interface MidiDevice {
  id: number;
  name: string;
}

interface MidiDevicesChangedEvent {
    /** Fresh input device snapshot after the topology change. */
    inputs: MidiDevice[];
    /** Fresh output device snapshot after the topology change. */
    outputs: MidiDevice[];
    /** Monotonically increasing generation for this callback registration. */
    generation: number;
}

// -- RTP-MIDI session info ---------------------------------------------------

interface RtpMidiSession {
    handle: number;
    name: string;
    port: number;
    state: "idle" | "listening" | "connecting" | "connected" | "closed" | "unknown";
    peerCount: number;
}

// -- File entry type ----------------------------------------------------------

interface FileEntry {
  name: string;
  type: "file" | "directory";
  size?: number;
}

interface PickedTextFile {
    name: string;
    text: string;
}

// -- Accelerometer data -------------------------------------------------------

interface AccelData {
  /** Acceleration along X axis (m/s²). */
  x: number;
  /** Acceleration along Y axis (m/s²). */
  y: number;
  /** Acceleration along Z axis (m/s²). */
  z: number;
}

// -- Compass data -------------------------------------------------------------

interface CompassData {
  /** Magnetic field along X axis (µT). */
  x: number;
  /** Magnetic field along Y axis (µT). */
  y: number;
  /** Magnetic field along Z axis (µT). */
  z: number;
  /** Compass heading in degrees (0 = north, 90 = east). */
  heading: number;
}

// -- Fetch / Network types ----------------------------------------------------

interface RequestInit {
  method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS";
  headers?: Record<string, string>;
  body?: string | ArrayBuffer;
}

interface Headers {
  get(name: string): string | null;
  has(name: string): boolean;
  entries(): [string, string][];
  keys(): string[];
  values(): string[];
  forEach(callback: (value: string, name: string) => void): void;
}

interface Response {
  readonly ok: boolean;
  readonly status: number;
  readonly statusText: string;
  readonly url: string;
  readonly redirected: boolean;
  readonly type: string;
  readonly headers: Headers;
  readonly bodyUsed: boolean;
  text(): string;
  json(): any;
  arrayBuffer(): ArrayBuffer;
}

interface CanvasTextureCanvas {
    /** Clear this offscreen canvas texture. */
    clear(color?: Color): void;
    /** Flush this offscreen canvas texture so its GL texture can be sampled. */
    flush(): void;
    /** Draw a filled/stroked rectangle into this offscreen canvas texture. */
    drawRect(x: number, y: number, width: number, height: number): void;
    /** Draw a filled/stroked circle into this offscreen canvas texture. */
    drawCircle(cx: number, cy: number, radius: number): void;
    /** Draw text into this offscreen canvas texture. */
    drawText(text: string, x: number, y: number, fontSize?: number): void;
}

interface CanvasTexture {
    /** Opaque CanvasTexture handle. */
    readonly id: number;
    /** Current width in pixels. */
    readonly width: number;
    /** Current height in pixels. */
    readonly height: number;
    /** Backing GL texture id. Pass the CanvasTexture object to sys.gl.bindCanvasTexture. */
    readonly texture: number;
    /** Backing GL framebuffer id. */
    readonly target: number;
    /** Skia drawing API for this offscreen texture. */
    readonly canvas: CanvasTextureCanvas;
    /** Flush pending Skia work so the backing GL texture can be sampled. */
    flush(): void;
    /** Resize this texture-backed Skia surface. */
    resize(width: number, height: number): void;
    /** Destroy the owned Skia surface, GL texture, and framebuffer. */
    destroy(): void;
}

// -- sys.gl namespace ---------------------------------------------------------

interface SysGL {
  // ---- 3D pipeline ----------------------------------------------------------

  /** Create a vertex or index buffer. If `data` is given, uploads it immediately. */
  createBuffer(target: "vertex" | "index", data?: ArrayBufferView, usage?: "static" | "dynamic" | "stream"): number;

  /** Replace the contents of an existing buffer (or a sub-range from `byteOffset`). */
  updateBuffer(bufferId: number, data: ArrayBufferView, byteOffset?: number): void;

  /** Destroy a buffer created with createBuffer. */
  destroyBuffer(bufferId: number): void;

  /** Create an empty 2D texture. If `pixels` is given, uploads RGBA8 data. */
  createTexture2D(width: number, height: number, format: "rgba8" | "rgb8" | "r8", pixels?: ArrayBufferView): number;

  /** Decode a PNG/JPG file from the project directory and upload it as a 2D texture. */
  loadTexture2D(path: string): number;

  /** Create a cubemap from 6 raw RGBA8 face buffers (order: +X, -X, +Y, -Y, +Z, -Z). */
  createTextureCube(size: number, format: "rgba8" | "rgb8" | "r8", faces: ArrayBufferView[]): number;

  /** Decode 6 image files (order: +X, -X, +Y, -Y, +Z, -Z) and upload them as a cubemap. */
  loadTextureCube(paths: [string, string, string, string, string, string]): number;

  /** Replace a sub-rectangle of a 2D texture with new pixel data. */
  updateTexture2D(textureId: number, x: number, y: number, w: number, h: number, pixels: ArrayBufferView): void;

  /** Destroy a texture created with createTexture2D / loadTexture2D / createTextureCube. */
  destroyTexture(textureId: number): void;

  /** Create an empty vertex layout. Returns a layout ID; bind attributes via setAttribute. */
  createVertexLayout(): number;

  /** Bind one vertex attribute slot to a buffer (use setIndexBuffer for the index buffer). */
  setAttribute(layoutId: number, location: number, bufferId: number, size: number, type: "float" | "u8" | "u16" | "u32" | "i8" | "i16" | "i32", normalized: boolean, stride: number, offset: number, divisor?: number): void;

  /** Attach an index buffer (u16 or u32) to a vertex layout. */
  setIndexBuffer(layoutId: number, bufferId: number, type: "u16" | "u32"): void;

  /** Destroy a vertex layout (does not destroy the underlying buffers). */
  destroyVertexLayout(layoutId: number): void;

  /** Look up the GLSL `layout(location=N)` of a named attribute in a program. */
  getAttribLocation(programId: number, name: string): number;

  /** Set a mat3 uniform from a 9-element Float32Array. */
  setUniformMatrix3(programId: number, name: string, mat9: Float32Array): void;

  /** Set a mat4 uniform from a 16-element Float32Array. */
  setUniformMatrix4(programId: number, name: string, mat16: Float32Array): void;

  /** Set a float-array uniform (1/2/3/4-component variants). */
  setUniform1fv(programId: number, name: string, values: Float32Array): void;
  setUniform2fv(programId: number, name: string, values: Float32Array): void;
  setUniform3fv(programId: number, name: string, values: Float32Array): void;
  setUniform4fv(programId: number, name: string, values: Float32Array): void;

  /** Set an int-array uniform. */
  setUniform1iv(programId: number, name: string, values: Int32Array): void;

  /** Bind a 2D texture (created via createTexture2D / loadTexture2D) to a sampler uniform. */
  bindTexture2D(programId: number, uniformName: string, textureId: number, textureUnit: number): void;

  /** Bind a cubemap texture to a sampler uniform. */
  bindTextureCube(programId: number, uniformName: string, textureId: number, textureUnit: number): void;

  /** Draw immediately against a vertex layout (with optional index buffer + GL state). */
  drawMesh(programId: number, layoutId: number, options: GLDrawOptions): void;

  /** Draw instanced geometry immediately. */
  drawMeshInstanced(programId: number, layoutId: number, options: GLDrawOptions, instanceCount: number): void;
}

interface GLDrawOptions {
  /** Primitive topology. Default: "triangles". */
  mode?: "triangles" | "triangle_strip" | "triangle_fan" | "lines" | "line_strip" | "points";
  /** First vertex (drawArrays) or index (drawElements). Default: 0. */
  first?: number;
  /** Vertex / index count. Required. */
  count: number;
  /** Optional render target id (default: backbuffer). */
  target?: number;
  /** Enable depth testing. Default: false. */
  depthTest?: boolean;
  /** Write to the depth buffer. Default: true when depthTest is true. */
  depthWrite?: boolean;
  /** Cull-face mode. Default: "none". */
  cull?: "none" | "back" | "front";
  /** Blend mode. Default: "none". */
  blend?: "none" | "alpha" | "add" | "premultiplied";
}

// Generated by scripts/generate-contract-artifacts.py. Do not edit.
// Source: api/contracts/{capabilities,device,math}.json

/** A stable capability availability entry. */
interface CapabilityEntry {
  readonly available: boolean;
}

/** Stable per-feature availability probes for the current process and platform. */
interface SysCapabilities {
  /** ONNX Runtime neural inference availability. */
  readonly neural: CapabilityEntry;
  /** Local GGUF inference through the optional llama.cpp subsystem. */
  readonly llamacpp: CapabilityEntry;
  /** Local MIDI and RTP-MIDI availability. */
  readonly midi: CapabilityEntry;
  /** Raw UDP datagram availability. */
  readonly udp: CapabilityEntry;
  /** HTTP fetch availability. */
  readonly http: CapabilityEntry;
  /** Accelerometer and compass availability. */
  readonly sensors: CapabilityEntry;
}

/** Device-level controls owned by the current application runtime. */
interface SysDevice {
  /** Request that the screen stays on, or release this application's request. Returns false when the platform cannot apply the change. */
  keepScreenOn(enabled: boolean): boolean;
}

/** In-place 3D math helpers. Matrices, vectors, and quaternions use caller-owned Float32Array storage; mat4 values are column-major. */
interface SysMath {
  mat4Identity(out: Float32Array): void;
  mat4Multiply(out: Float32Array, a: Float32Array, b: Float32Array): void;
  mat4Perspective(out: Float32Array, fovy: number, aspect: number, near: number, far: number): void;
  mat4Ortho(out: Float32Array, left: number, right: number, bottom: number, top: number, near: number, far: number): void;
  mat4LookAt(out: Float32Array, eye: Float32Array, target: Float32Array, up: Float32Array): void;
  mat4Translate(out: Float32Array, a: Float32Array, translation: Float32Array): void;
  mat4RotateX(out: Float32Array, a: Float32Array, angle: number): void;
  mat4RotateY(out: Float32Array, a: Float32Array, angle: number): void;
  mat4RotateZ(out: Float32Array, a: Float32Array, angle: number): void;
  mat4Scale(out: Float32Array, a: Float32Array, scale: Float32Array): void;
  /** Returns true when the matrix is invertible. */
  mat4Invert(out: Float32Array, a: Float32Array): boolean;
  mat4Transpose(out: Float32Array, a: Float32Array): void;
  vec3Add(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Sub(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Scale(out: Float32Array, a: Float32Array, scale: number): void;
  vec3Normalize(out: Float32Array, a: Float32Array): void;
  vec3Cross(out: Float32Array, a: Float32Array, b: Float32Array): void;
  vec3Dot(a: Float32Array, b: Float32Array): number;
  vec3Length(a: Float32Array): number;
  /** Transforms a vec3 as (x, y, z, 1) and applies perspective division. */
  vec3TransformMat4(out: Float32Array, value: Float32Array, matrix: Float32Array): void;
  /** Normalizes count tightly packed vec3 values in one native call. */
  vec3NormalizeMany(out: Float32Array, values: Float32Array, count: number): void;
  /** Transforms count tightly packed vec3 values by one matrix in one native call. */
  vec3TransformMat4Many(out: Float32Array, values: Float32Array, matrix: Float32Array, count: number): void;
  quatFromAxisAngle(out: Float32Array, axis: Float32Array, angle: number): void;
  quatMultiply(out: Float32Array, a: Float32Array, b: Float32Array): void;
  quatSlerp(out: Float32Array, a: Float32Array, b: Float32Array, t: number): void;
  quatToMat4(out: Float32Array, value: Float32Array): void;
}

// -- sys.canvas object --------------------------------------------------------

interface SysCanvas {
  /** Clear the entire canvas with the given color. */
  clear(color?: Color): void;

  /** Draw a filled/stroked rectangle. */
  drawRect(x: number, y: number, width: number, height: number): void;

  /** Draw a filled/stroked circle. */
  drawCircle(cx: number, cy: number, radius: number): void;

  /** Draw text at the given position. The default font size is 32. */
  drawText(text: string, x: number, y: number, fontSize?: number): void;

  /** Read the canvas's current pixel content back from the GPU. Returns RGBA8 premultiplied pixels in row-major top-to-bottom order. Implicitly flushes pending draws and stalls until the GPU has finished, so use sparingly. Useful for screenshots, image processing, and procedural content generation that needs to inspect what was just drawn. */
  readPixels(): { width: number, height: number, pixels: ArrayBuffer };

  /** Draw a filled/stroked rounded rectangle. */
  drawRoundRect(x: number, y: number, width: number, height: number, rx: number, ry: number): void;

  /** Draw a filled/stroked oval inscribed in the given rectangle. */
  drawOval(x: number, y: number, width: number, height: number): void;

  /** Draw a line segment. */
  drawLine(x1: number, y1: number, x2: number, y2: number): void;

  /** Draw a single point. */
  drawPoint(x: number, y: number): void;

  drawPath(arg1: any): any;

  /** Draw an arc. Angles in degrees. If useCenter is true, draws a pie-shaped wedge. */
  drawArc(x: number, y: number, width: number, height: number, startAngle: number, sweepAngle: number, useCenter?: boolean): void;

  drawSvg(arg1: any, arg2: any, arg3: any, arg4: any, arg5: any): any;

  /** Measure text width in pixels using the active font. The default font size is 32. */
  measureText(text: string, fontSize?: number): number;

  /** Measure text bounds in pixels using the active font. The default font size is 32. */
  measureTextRect(text: string, fontSize?: number): { width: number, height: number };

  /** Set the fill color and switch paint style to fill. */
  setFillColor(color: Color): void;

  /** Set the stroke color and switch paint style to stroke. */
  setStrokeColor(color: Color): void;

  /** Set the stroke width. */
  setStrokeWidth(width: number): void;

  /** Enable or disable anti-aliasing. */
  setAntiAlias(enabled: boolean): void;

  /** Set paint alpha (0–255). */
  setAlpha(alpha: number): void;

  /** Set the stroke cap style. */
  setStrokeCap(cap: "butt" | "round" | "square"): void;

  /** Set the stroke join style. */
  setStrokeJoin(join: "miter" | "round" | "bevel"): void;

  /** Set the SkBlendMode used when compositing. Throws RangeError on an unknown mode name. */
  setBlendMode(mode: "src-over" | "src" | "dst-over" | "dst-in" | "dst-out" | "src-in" | "src-out" | "clear" | "plus" | "multiply" | "screen" | "overlay" | "darken" | "lighten" | "color-dodge" | "color-burn" | "hard-light" | "soft-light" | "difference" | "exclusion" | "hue" | "saturation" | "color" | "luminosity"): boolean;

  /** Attach a Skia image-filter to the default paint, or clear it. Forms: `setImageFilter("blur", sigmaX, sigmaY?)`; `setImageFilter("drop-shadow", dx, dy, sigmaX, sigmaY?, color)` (color is ARGB number or "#RRGGBBAA"); `setImageFilter("drop-shadow-only", dx, dy, sigmaX, sigmaY?, color)` (same args, but only the shadow is rasterised -- the original paint output is dropped, useful for composing shadows under separately drawn elements); `setImageFilter("none")` / `setImageFilter(null)` / `setImageFilter()` to clear.`. Throws TypeError on missing required arguments and RangeError on an unknown filter name. */
  setImageFilter(name?: "blur" | "drop-shadow" | "drop-shadow-only" | "none" | null, ...args: (number | string)[]): boolean;

  /** Attach a Skia color-filter to the default paint, or clear it. Forms: `setColorFilter("matrix", m)` where `m` is an array-like of exactly 20 numbers (4x5 row-major matrix applied as `[Rout Gout Bout Aout]^T = M * [R G B A 1]^T`, channels in 0..1, last column is the bias term); `setColorFilter("blend", color, blendModeName)` composes the source with `color` (ARGB number or "#RRGGBBAA") using one of the names accepted by `setBlendMode`; `setColorFilter("none")` / `setColorFilter(null)` / `setColorFilter()` to clear. Throws TypeError on missing / wrong-typed arguments and RangeError on an unknown filter or blend mode name. */
  setColorFilter(name?: "matrix" | "blend" | "none" | null, ...args: (number | string | ArrayLike<number>)[]): boolean;

  setFont(arg1: any): any;

  /** Save the current transform and clip state onto a stack. */
  save(): void;

  /** Restore the most recently saved transform/clip state. */
  restore(): void;

  /** Translate the canvas origin. */
  translate(dx: number, dy: number): void;

  /** Rotate the canvas. If px/py are given, rotate around that point. */
  rotate(degrees: number, px?: number, py?: number): void;

  /** Scale the canvas. */
  scale(sx: number, sy: number): void;

  /** Skew the canvas. */
  skew(sx: number, sy: number): void;

  /** Reset the transform to identity. */
  reset(): void;

  /** Clip drawing to a rectangle. */
  clipRect(x: number, y: number, width: number, height: number): void;

}

// -- sys.graphics object ------------------------------------------------------

interface SysGraphics {
  /** Create an offscreen Skia canvas backed by a GL texture and framebuffer. */
  createCanvasTexture(width: number, height: number): CanvasTexture;

}

// -- sys.path object ----------------------------------------------------------

interface SysPath {
  /** Create a new empty path. Returns an opaque integer path ID. */
  create(): number;

  /** Reset a path to empty. */
  reset(pathId: number): void;

  /** Move the path cursor to (x, y). */
  moveTo(pathId: number, x: number, y: number): void;

  /** Add a line segment to (x, y). */
  lineTo(pathId: number, x: number, y: number): void;

  /** Add a quadratic Bézier curve. */
  quadTo(pathId: number, x1: number, y1: number, x2: number, y2: number): void;

  /** Add a cubic Bézier curve. */
  cubicTo(pathId: number, x1: number, y1: number, x2: number, y2: number, x3: number, y3: number): void;

  /** Close the current subpath. */
  close(pathId: number): void;

  /** Add a rectangle subpath. */
  addRect(pathId: number, x: number, y: number, width: number, height: number): void;

  /** Add a circle subpath. */
  addCircle(pathId: number, cx: number, cy: number, radius: number): void;

}

// -- sys.svg object -----------------------------------------------------------

interface SysSVG {
  /** Load an SVG image from a file. Returns a non-negative SVG ID on success, -1 on failure. */
  load(path: string): number;

  /** Load an SVG image from an ArrayBuffer or TypedArray. Returns a non-negative SVG ID on success, -1 on failure. */
  loadFromBuffer(buffer: ArrayBuffer | ArrayBufferView): number;

  /** Destroy a loaded SVG and free its resources. */
  destroy(svgId: number): void;

  /** Get the intrinsic width of a loaded SVG. */
  getWidth(svgId: number): number;

  /** Get the intrinsic height of a loaded SVG. */
  getHeight(svgId: number): number;

}

// -- sys.font object ----------------------------------------------------------

interface SysFont {
  /** Load a font file from the project directory. */
  load(path: string, name?: string): void;

  /** Load a font from an ArrayBuffer or TypedArray and register it under an optional name. */
  loadFromBuffer(buffer: ArrayBuffer | ArrayBufferView, name?: string): void;

}

// -- sys.input object ---------------------------------------------------------

interface SysInput {
  /** Get the current frame's input state. */
  get(): InputState;

  /** Check whether a key is currently held down (SDL scancode). */
  isKeyDown(scancode: number): boolean;

  /** Check whether a key was pressed this frame (SDL scancode). */
  isKeyPressed(scancode: number): boolean;

  /** Start a platform text-editing session and show the soft keyboard where applicable. */
  startTextInput(options: TextInputOptions): boolean;

  /** Synchronize text, UTF-16 selection, and candidate-window caret geometry. */
  updateTextInput(options: TextInputOptions): boolean;

  /** Finish composition and stop the active platform text-editing session. */
  stopTextInput(): void;

}

// -- sys.window object --------------------------------------------------------

interface SysWindow {
  /** Canvas width in pixels. */
  getWidth(): number;

  /** Canvas height in pixels. */
  getHeight(): number;

  /** Display density scaling factor. Returns 1.0 on desktop, device density on Android. */
  getDisplayDensity(): number;

}

// -- sys.animation object -----------------------------------------------------

interface SysAnimation {
  /** Register a callback to be invoked on the next frame. Returns a handle. */
  requestFrame(callback: (timestamp: number) => void): number;

  /** Cancel the stored animation callback. */
  cancelFrame(handle: number): void;

}

// -- sys.timer object ---------------------------------------------------------

interface SysTimer {
}

// -- sys.audio object ---------------------------------------------------------

interface SysAudio {
  /** Noise (4). */
  readonly NOISE: 4;
  /** Sawtooth wave (2). */
  readonly SAWTOOTH: 2;
  /** Sine wave (0). */
  readonly SINE: 0;
  /** Square wave (1). */
  readonly SQUARE: 1;
  /** Triangle wave (3). */
  readonly TRIANGLE: 3;

  /** Start the audio context. */
  start(): void;

  /** Stop the audio context. */
  stop(): void;

  /** Check whether audio is currently playing. */
  isPlaying(): boolean;

  /** Set master output gain. Clamped to 0.0–1.0. Default is 0.5. */
  setMasterGain(gain: number): void;

  /** Get the current master gain. */
  getMasterGain(): number;

  /** Create a new oscillator. Returns an oscillator ID. */
  createOscillator(): number;

  /** Destroy an oscillator and release its resources. */
  destroyOscillator(oscId: number): void;

  /** Set the waveform type of an oscillator. */
  setOscillatorType(oscId: number, type: number | "sine" | "square" | "sawtooth" | "triangle" | "noise"): void;

  /** Set oscillator frequency in Hz. */
  setOscillatorFrequency(oscId: number, freq: number): void;

  /** Set oscillator gain (0.0–1.0). */
  setOscillatorGain(oscId: number, gain: number): void;

  /** Set oscillator pitch detune in cents. */
  setOscillatorDetune(oscId: number, cents: number): void;

  /** Start an oscillator. Starts the audio context if needed. */
  startOscillator(oscId: number): void;

  /** Stop an oscillator. */
  stopOscillator(oscId: number): void;

  /** Configure the ADSR envelope on an oscillator. Times in seconds, sustain is 0.0–1.0. */
  setOscillatorEnvelope(oscId: number, attack: number, decay: number, sustain: number, release: number): void;

  /** Trigger the attack phase of the envelope. Starts audio if needed. */
  noteOn(oscId: number): void;

  /** Trigger the release phase of the envelope. */
  noteOff(oscId: number): void;

  /** Load a WAV, MP3, Ogg Vorbis, or FLAC asset into an audio buffer. Returns a buffer ID, or -1 on failure. */
  loadBuffer(path: string): number;

  /** Decode WAV, MP3, Ogg Vorbis, or FLAC bytes from an ArrayBuffer into an audio buffer. Returns a buffer ID, or -1 on failure. */
  loadBufferFromBuffer(buffer: ArrayBuffer): number;

  /** Create an audio buffer. Returns a buffer ID. */
  createBuffer(sampleRate: number, channels: number, numSamples: number): number;

  /** Fill a buffer with sample data. Samples are floats from -1.0 to 1.0. */
  setBufferData(bufferId: number, samples: number[], offset?: number): void;

  /** Destroy an audio buffer. */
  destroyBuffer(bufferId: number): void;

  /** Play an audio buffer. Returns a playback ID. */
  playBuffer(bufferId: number, loop?: boolean, gain?: number): number;

  /** Stop a currently playing buffer. */
  stopBuffer(playbackId: number): void;

  /** Convert a MIDI note number to frequency in Hz (A4 = 440 Hz). */
  midiToFreq(midiNote: number): number;

  /** Return the most recent audio error message. */
  getError(): string;

}

// -- sys.midi object ----------------------------------------------------------

interface SysMidi {
  readonly CC_ALL_NOTES_OFF: 123;
  readonly CC_ALL_SOUND_OFF: 120;
  readonly CC_BREATH: 2;
  readonly CC_EXPRESSION: 11;
  readonly CC_FOOT: 4;
  readonly CC_MOD_WHEEL: 1;
  readonly CC_PAN: 10;
  readonly CC_SUSTAIN: 64;
  readonly CC_VOLUME: 7;
  /** Channel Pressure (0xD0). */
  readonly CHANNEL_PRESSURE: 0xD0;
  /** Control Change (0xB0). */
  readonly CONTROL_CHANGE: 0xB0;
  /** Note Off (0x80). */
  readonly NOTE_OFF: 0x80;
  /** Note On (0x90). */
  readonly NOTE_ON: 0x90;
  /** Pitch Bend (0xE0). */
  readonly PITCH_BEND: 0xE0;
  /** Polyphonic Key Pressure (0xA0). */
  readonly POLY_PRESSURE: 0xA0;
  /** Program Change (0xC0). */
  readonly PROGRAM_CHANGE: 0xC0;
  /** System Exclusive (0xF0). */
  readonly SYSEX: 0xF0;

  /** Number of available MIDI input devices. */
  getInputCount(): number;

  /** Number of available MIDI output devices. */
  getOutputCount(): number;

  /** List available MIDI input devices. */
  getInputDevices(): MidiDevice[];

  /** List available MIDI output devices. */
  getOutputDevices(): MidiDevice[];

  /** Rescan available MIDI devices. */
  refreshDevices(): void;

  /** Replace the device-topology listener, or pass null to unsubscribe. The callback runs on the runtime frame thread after a real input/output topology change. */
  onDevicesChanged(callback: ((event: MidiDevicesChangedEvent) => void) | null): void;

  /** Open a MIDI input port and start receiving messages. Returns an input handle. */
  openInput(deviceIndex: number, callback: (msg: MidiMessage) => void): number;

  /** Close a MIDI input handle. */
  closeInput(handle: number): void;

  /** Open a MIDI output port. Returns a handle, or -1 on failure. */
  openOutput(deviceIndex: number): number;

  /** Close a MIDI output handle. */
  closeOutput(handle: number): void;

  /** Send a raw 3-byte MIDI message. Returns true on success. */
  sendMessage(handle: number, status: number, data1: number, data2: number): boolean;

  /** Send a raw MIDI byte sequence, including SysEx. Returns true on success. */
  sendRaw(handle: number, bytes: ArrayLike<number>): boolean;

  /** Send a Note On message. Channel is 0–15. Returns true on success. */
  noteOn(handle: number, channel: number, note: number, velocity: number): boolean;

  /** Send a Note Off message. Channel is 0–15. Returns true on success. */
  noteOff(handle: number, channel: number, note: number, velocity: number): boolean;

  /** Send a Control Change message. Returns true on success. */
  controlChange(handle: number, channel: number, control: number, value: number): boolean;

  /** Send a Program Change message. Returns true on success. */
  programChange(handle: number, channel: number, program: number): boolean;

  /** Send a Pitch Bend message. Value is -8192 to 8191. Returns true on success. */
  pitchBend(handle: number, channel: number, value: number): boolean;

  /** Send a Channel Pressure message. Returns true on success. */
  channelPressure(handle: number, channel: number, pressure: number): boolean;

  /** Send a Polyphonic Key Pressure message. Returns true on success. */
  polyPressure(handle: number, channel: number, note: number, pressure: number): boolean;

  /** Extract the message type from a MIDI status byte. */
  getType(status: number): number;

  /** Extract the channel (0–15) from a MIDI status byte, or -1 for system. */
  getChannel(status: number): number;

  /** Create an RTP-MIDI session. Pass port 0 or omit it to let the runtime choose. Returns a session handle, or -1 on failure. */
  createSession(name: string, port?: number): number;

  /** Invite/connect an RTP-MIDI session to a remote host and port. */
  connectSession(session: number, host: string, port: number): boolean;

  /** Destroy an RTP-MIDI session and unregister its callback. */
  destroySession(session: number): void;

  /** Register a callback for incoming RTP-MIDI messages on a session. */
  onSessionMessage(session: number, callback: (msg: MidiMessage) => void): void;

  /** Send a raw 3-byte RTP-MIDI message through a session. Returns true on success. */
  sessionSend(session: number, status: number, data1: number, data2: number): boolean;

  /** Send an RTP-MIDI Note On message. Returns true on success. */
  sessionNoteOn(session: number, channel: number, note: number, velocity: number): boolean;

  /** Send an RTP-MIDI Note Off message. Returns true on success. */
  sessionNoteOff(session: number, channel: number, note: number, velocity: number): boolean;

  /** Send an RTP-MIDI Control Change message. Returns true on success. */
  sessionControlChange(session: number, channel: number, control: number, value: number): boolean;

  /** Send a raw RTP-MIDI byte sequence through a session. Returns true on success. */
  sessionSendRaw(session: number, bytes: ArrayLike<number>): boolean;

  /** Return information for active RTP-MIDI sessions. */
  getSessions(): RtpMidiSession[];

}

// -- sys.db object ------------------------------------------------------------

interface SysDB {
  /** Open (or create) a named database. Returns a database handle. Throws on failure. */
  open(name: string): number;

  /** Close a database handle. */
  close(handle: number): void;

  /** Execute a SQL statement (no result set). Throws on failure. */
  execute(handle: number, sql: string): boolean;

  /** Execute a parameterized SQL statement. Returns the number of changed rows. Throws on failure. */
  run(handle: number, sql: string, ...params: (string | number | boolean | null)[]): number;

  /** Execute a parameterized SQL query. Returns an array of row objects. */
  query(handle: number, sql: string, ...params: (string | number | boolean | null)[]): Record<string, any>[];

  /** Get the row ID of the last inserted row. */
  lastInsertId(handle: number): number;

  /** Get the last SQLite error message. */
  getError(): string;

}

// -- sys.files object ---------------------------------------------------------

interface SysFiles {
  /** List entries at a virtual path. The root contains assets/ and files/. */
  list(path?: string): FileEntry[];

  /** Read an assets/... or files/... path as UTF-8 text. Throws on error. */
  readText(path: string): string;

  /** Read an assets/... or files/... path as binary data. Returns an ArrayBuffer. Throws on error. */
  readBinary(path: string): ArrayBuffer;

  /** Write UTF-8 text to a files/... path, creating parents and replacing any existing file. assets/... is read-only. Returns the absolute saved path. On web this triggers a browser download. Throws on error. */
  writeText(path: string, text: string): string;

  /** Write binary data to a files/... path, creating parents and replacing any existing file. assets/... is read-only. Returns the absolute saved path. On web this triggers a browser download. Throws on error. */
  writeBinary(path: string, data: ArrayBuffer | ArrayBufferView): string;

  /** Append binary data to a files/... path, creating it and its parents when needed. assets/... is read-only. Returns the absolute saved path. Throws on error. */
  appendBinary(path: string, data: ArrayBuffer | ArrayBufferView): string;

  /** Check if a path exists and is a regular file. */
  exists(path: string): boolean;

  /** Check if a path exists and is a directory. */
  isDirectory(path: string): boolean;

  /** Get the size of a file in bytes. Throws on error. */
  size(path: string): number;

  /** Open a native/system text-file picker. Returns false if unavailable or another picker is active. Selected files are capped at 8 MiB. */
  pickText(callback: (file: PickedTextFile | null, error: string | null) => void): boolean;

  saveText(arg1: any, arg2: any, arg3: any): any;

  /** Get the last file error message. */
  getError(): string;

  /** List entries at a virtual path. The root contains assets/ and files/. */
  list(path?: string): FileEntry[];

  /** Read an assets/... or files/... path as UTF-8 text. Throws on error. */
  readText(path: string): string;

  /** Read an assets/... or files/... path as binary data. Returns an ArrayBuffer. Throws on error. */
  readBinary(path: string): ArrayBuffer;

  /** Check if a path exists and is a regular file. */
  exists(path: string): boolean;

  /** Check if a path exists and is a directory. */
  isDirectory(path: string): boolean;

  /** Get the size of a file in bytes. Throws on error. */
  size(path: string): number;

  /** Get the last file error message. */
  getError(): string;

}

// -- sys.assets object --------------------------------------------------------

interface SysAssets {
  /** List entries at a virtual path. The root contains assets/ and files/. */
  list(path?: string): FileEntry[];

  /** Read an assets/... or files/... path as UTF-8 text. Throws on error. */
  readText(path: string): string;

  /** Read an assets/... or files/... path as binary data. Returns an ArrayBuffer. Throws on error. */
  readBinary(path: string): ArrayBuffer;

  /** Check if a path exists and is a regular file. */
  exists(path: string): boolean;

  /** Check if a path exists and is a directory. */
  isDirectory(path: string): boolean;

  /** Get the size of a file in bytes. Throws on error. */
  size(path: string): number;

  /** Get the last file error message. */
  getError(): string;

}

// -- sys.sensors object -------------------------------------------------------

interface SysMagneto {
  /** Check if any motion sensors are present. Returns false on desktop. */
  isAvailable(): boolean;

  /** Check if an accelerometer sensor is available. */
  hasAccelerometer(): boolean;

  /** Check if a magnetometer (compass) sensor is available. */
  hasCompass(): boolean;

  /** Start sensor updates. Returns true on success, false on desktop. */
  start(): boolean;

  /** Stop sensor updates. */
  stop(): void;

  /** Check if sensors are currently running. */
  isActive(): boolean;

  /** Get the latest accelerometer reading, or null if unavailable. */
  getAccel(): AccelData | null;

  /** Get the latest compass reading, or null if unavailable. */
  getCompass(): CompassData | null;

}

// -- sys.neural object --------------------------------------------------------

// -- Neural inference types --------------------------------------------------

/** Shape and type information for a single model tensor. */
interface TensorInfo {
  /** Tensor name as declared in the ONNX graph. */
  name: string;
  /** Dimension sizes. -1 indicates a dynamic dimension. */
  shape: number[];
  /** Element type: "float32" | "int32" | "int64" | "uint8" */
  dtype: string;
}

/** ONNX model metadata returned by sys.neural.getModelInfo(). */
interface ModelInfo {
  description:  string;
  producerName: string;
  graphName:    string;
  domain:       string;
  version:      number;
  inputs:       TensorInfo[];
  outputs:      TensorInfo[];
}

interface SysNeural {
  /** Returns true if ONNX Runtime was compiled in (ENABLE_NEURAL=ON). */
  isAvailable(): boolean;

  /** Returns the last error message from the neural subsystem, or an empty string. */
  getError(): string;

  /** Load a model from a path relative to the project directory. Only .onnx files are supported. Returns a non-negative model ID. Throws on failure. */
  loadModel(path: string): number;

  /** Load an ONNX model from an ArrayBuffer or TypedArray. Returns a non-negative model ID. Throws on failure. */
  loadModelFromBuffer(buffer: ArrayBuffer | ArrayBufferView): number;

  /** Unload a previously loaded model and free its session. */
  unloadModel(modelId: number): void;

  /** Return metadata describing the model's inputs, outputs, shapes, dtypes, and version. Throws on failure. */
  getModelInfo(modelId: number): ModelInfo;

  /**
    * Stage an input tensor for the next `run()` call.
   * The optional `shape` argument is accepted for API symmetry with WASM and ignored
   * when the model declares a fully-static shape.
   */
  setInput(modelId: number, name: string, data: Float32Array | Int32Array | BigInt64Array | Uint8Array, shape?: number[]): void;

  /**
    * Read a previously-staged or just-produced output tensor by name. Returns the
    * same TypedArray flavour as the model output declares.
   */
  getOutput(modelId: number, name: string): Float32Array | Int32Array | BigInt64Array | Uint8Array;

  /**
    * Run inference, optionally accepting an inputs map directly and returning
    * the outputs map.
   */
  run(modelId: number, inputs?: Record<string, Float32Array | Int32Array | BigInt64Array | Uint8Array>): Record<string, Float32Array | Int32Array | BigInt64Array | Uint8Array>;

}

// -- sys.llamacpp object ------------------------------------------------------

type LlamaCppRole = "system" | "user" | "assistant";
interface LlamaCppMessage { role: LlamaCppRole; content: string; }
interface LlamaCppLoadOptions {
  contextSize?: number; device?: "auto" | "cpu" | string;
  gpuLayers?: "auto" | number; threads?: "auto" | number;
  batchSize?: "auto" | number; useMmap?: boolean; allowFallback?: boolean;
}
interface LlamaCppGenerateOptions {
  maxTokens?: number; minTokens?: number; temperature?: number; topK?: number; topP?: number;
  minP?: number; repetitionPenalty?: number; seed?: number; stop?: string[];
}
interface LlamaCppResult {
  finishReason: "stop" | "length" | "cancelled"; text: string;
  promptTokens: number; generatedTokens: number;
  promptTokensPerSecond: number; generatedTokensPerSecond: number;
}
interface LlamaCppStreamCallbacks {
  onText(text: string): void;
  onComplete(result: LlamaCppResult): void;
  onError(error: Error): void;
}
interface LlamaCppGeneration { readonly running: boolean; cancel(): void; }
interface LlamaCppChat {
  send(text: string, options: LlamaCppGenerateOptions, callbacks: LlamaCppStreamCallbacks): LlamaCppGeneration;
  send(text: string, callbacks: LlamaCppStreamCallbacks): LlamaCppGeneration;
  getMessages(): LlamaCppMessage[]; clear(): void; cancel(): void; destroy(): void;
}
interface LlamaCppModelInfo {
  name: string; architecture: string; quantization: string; parameterCount: number;
  fileSize: number; modelContextSize: number; activeContextSize: number;
  vocabularySize: number; chatTemplate: string; backend: string; device: string;
  gpuLayers: number; totalLayers: number; estimatedMemoryBytes: number; fallbackReason: string;
}
interface LlamaCppModel {
  getInfo(): LlamaCppModelInfo;
  createChat(options?: { systemPrompt?: string; contextSize?: number }): LlamaCppChat;
  destroy(): void;
}
interface LlamaCppDeviceInfo {
  id: string; backend: string; name: string; available: boolean;
  memoryBytes: number | null; reason: string;
}
interface SysLlamaCpp {
  isAvailable(): boolean; getDevices(): LlamaCppDeviceInfo[];
  loadModel(path: string, callback: (model: LlamaCppModel | null, error: Error | null) => void): void;
  loadModel(path: string, options: LlamaCppLoadOptions, callback: (model: LlamaCppModel | null, error: Error | null) => void): void;
  getError(): string;
}

// -- sys.net.udp object -----------------------------------------------------------

/** A datagram delivered to a `sys.net.udp.onMessage` callback. */
interface UdpMessage {
  /** The raw datagram bytes. */
  data: Uint8Array;
  /** The remote host (numeric IP string). */
  host: string;
  /** The remote port. */
  port: number;
}

interface SysUDP {
  /**
   * Bind a UDP socket on the given port. Pass `0` to let the OS pick a free port
   * (use `getPort()` afterwards to discover it). Returns a non-negative socket id,
   * or `-1` on transient failure (port busy, permission denied, …).
   */
  bind(port: number): number;

  /** Return the actual port a previously-bound socket is listening on, or `-1`. */
  getPort(socketId: number): number;

  /**
   * Send a datagram to `host:port`. `data` may be a string (UTF-8 encoded) or a
   * TypedArray / ArrayBuffer. Returns the number of bytes sent, or `-1` on failure.
   */
  send(socketId: number, host: string, port: number, data: string | ArrayBuffer | ArrayBufferView): number;

  /**
   * Register a callback invoked once per pending datagram during the per-frame
   * polling pass. Pass `null` to unregister.
   */
  onMessage(socketId: number, callback: ((msg: UdpMessage) => void) | null): void;

  /** Close a socket and release its OS resources. */
  close(socketId: number): void;
}

// -- sys.net object -------------------------------------------------------

interface SysNetwork {
  /** Perform an HTTP request (synchronous). Requires network policy in app.json. */
  fetch(url: string, options?: RequestInit): Response;

}

// -- sys namespace ------------------------------------------------------------

interface Sys {
  /** 2D drawing primitives and paint style settings. */
  readonly canvas: SysCanvas;
  /** Path creation and manipulation. */
  readonly path: SysPath;
  /** SVG loading and drawing. */
  readonly svg: SysSVG;
  /** Font loading and selection. */
  readonly font: SysFont;
  /** Texture-backed Skia surfaces. */
  readonly graphics: SysGraphics;
  /** OpenGL shader pass API. */
  readonly gl: SysGL;
  /** In-place 3D math (vec3, quat, mat4) — gl-matrix style. */
  readonly math: SysMath;
  /** Input state (pointer, keyboard, timing). */
  readonly input: SysInput;
  /** Window dimensions and display density. */
  readonly window: SysWindow;
  /** Animation frame scheduling. */
  readonly animation: SysAnimation;
  /** Delayed and repeating callback timers. */
  readonly timer: SysTimer;
  /** Audio synthesis engine. */
  readonly audio: SysAudio;
  /** MIDI input/output. */
  readonly midi: SysMidi;
  /** SQLite database persistence. */
  readonly db: SysDB;
  /** Virtual filesystem containing read-only assets/ and writable files/. */
  readonly files: SysFiles;
  /** Read-only convenience wrapper over the sys.files assets/ mount. */
  readonly assets: SysAssets;
  /** HTTP networking. */
  readonly network: SysNetwork;
  /** Accelerometer and compass sensors. */
  readonly magneto: SysMagneto;
  /** Device-level controls. */
  readonly device: SysDevice;
  /** UDP datagram sockets. */
  readonly udp: SysUDP;
  /** Per-feature availability probes. */
  readonly capabilities: SysCapabilities;
  /** ONNX Runtime neural network inference (requires "neural": true in app.json). */
  readonly neural: SysNeural;
  /** Optional local GGUF inference through llama.cpp (desktop managed runtimes only). */
  readonly llamacpp: SysLlamaCpp;
}

// -- Global declarations ------------------------------------------------------

/** The Budo runtime system namespace. */
declare const sys: Sys;

/** Console output (stdout). */
declare const console: {
};

