#!/usr/bin/env python3
"""Generate checked-in type and support artifacts from managed API contracts."""

import argparse
import html
import importlib.util
import json
import sys
from pathlib import Path


PILOT_SUBSYSTEMS = ("capabilities", "device", "math", "accessibility")
API_AVAILABILITY_START = "<!-- BEGIN GENERATED API AVAILABILITY -->"
API_AVAILABILITY_END = "<!-- END GENERATED API AVAILABILITY -->"
RUNTIME_LABELS = {
    "javascript": "JavaScript",
    "lua": "Lua",
    "wasmtime": "Wasmtime",
    "browser_wasm": "Browser WASM",
}
TYPE_MAP = {
    "bool": "boolean",
    "string": "string",
    "string|null": "string | null",
    "haptic": '"light" | "medium" | "heavy" | "selection" | "success" | "warning" | "error"',
    "cursor": '"default" | "text" | "pointer" | "grab" | "grabbing" | "move" | "ew-resize" | "ns-resize" | "nwse-resize" | "nesw-resize" | "not-allowed" | "wait" | "crosshair" | "none"',
    "preferences": "DevicePreferences",
    "nodes": "AccessibilityNode[]",
    "actions": "AccessibilityAction[]",
    "f32": "number",
    "i32": "number",
    "mat4": "Float32Array",
    "quat": "Float32Array",
    "vec3": "Float32Array",
    "vec3[]": "Float32Array",
    "void": "void",
}


def load_validator(root):
    path = root / "scripts" / "validate-api-contracts.py"
    spec = importlib.util.spec_from_file_location("validate_api_contracts", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_contracts(root):
    contracts = {}
    for path in sorted((root / "api" / "contracts").glob("*.json")):
        contract = json.loads(path.read_text(encoding="utf-8"))
        contracts[contract["subsystem"]] = contract
    return contracts


def build_support_matrix(root, contracts):
    validator = load_validator(root)
    errors = []
    loaded = []
    matrix = {"version": 1, "subsystems": {}}
    for subsystem, contract in sorted(contracts.items()):
        path = root / "api" / "contracts" / f"{subsystem}.json"
        loaded.append((path, contract))
        summary = validator.validate_contract(root, path, contract, errors)
        if summary is not None:
            matrix["subsystems"][subsystem] = summary
    validator.validate_capability_gates(root, loaded, errors)
    validator.validate_wrapper_ownership(root, loaded, errors)
    if errors:
        raise ValueError("\n".join(errors))
    return matrix


def javascript_export(operation):
    export = operation.get("exports", {}).get("javascript")
    if isinstance(export, str):
        return export
    if isinstance(export, dict):
        return export.get("name")
    raise ValueError(f"{operation.get('name')}: missing singular JavaScript export")


def map_type(value):
    mapped = TYPE_MAP.get(value.strip())
    if not mapped:
        raise ValueError(f"unsupported contract type for TypeScript generation: {value}")
    return mapped


def parse_signature(signature):
    if not isinstance(signature, str) or "->" not in signature:
        raise ValueError(f"unsupported contract signature: {signature!r}")
    parameters_text, return_text = (part.strip() for part in signature.split("->", 1))
    if not (parameters_text.startswith("(") and parameters_text.endswith(")")):
        raise ValueError(f"unsupported parameter list: {signature}")
    parameters = []
    body = parameters_text[1:-1].strip()
    if body:
        for parameter in body.split(","):
            parameter = parameter.strip()
            if ":" in parameter:
                name, type_name = (part.strip() for part in parameter.split(":", 1))
            else:
                parts = parameter.split()
                if len(parts) != 2:
                    raise ValueError(f"unsupported parameter: {parameter}")
                type_name, name = parts
            parameters.append((name, map_type(type_name)))
    return parameters, map_type(return_text)


def render_types(contracts):
    lines = [
        "// Generated by scripts/generate-contract-artifacts.py. Do not edit.",
        "// Source: api/contracts/{capabilities,device,math,accessibility}.json",
        "",
        "/** A stable capability availability entry. */",
        "interface CapabilityEntry {",
        "  readonly available: boolean;",
        "}",
        "",
        "/** One element exposed to screen readers by sys.accessibility.update(). */",
        "interface AccessibilityNode {",
        "  /** Stable id, returned with the actions on this node. */",
        "  id: string;",
        "  role: \"button\" | \"checkbox\" | \"radio\" | \"switch\" | \"slider\" | \"textbox\" | \"list\" | \"listitem\" | \"heading\" | \"text\" | \"combobox\" | \"option\" | \"tab\" | \"image\" | \"group\" | \"link\";",
        "  /** What a screen reader announces. */",
        "  label: string;",
        "  /** Text of fields, or a readable slider value. */",
        "  value?: string;",
        "  /** Bounds in physical canvas pixels. */",
        "  x: number;",
        "  y: number;",
        "  width: number;",
        "  height: number;",
        "  checked?: boolean;",
        "  selected?: boolean;",
        "  focused?: boolean;",
        "  disabled?: boolean;",
        "  expanded?: boolean;",
        "  /** Sliders: range and current value. */",
        "  min?: number;",
        "  max?: number;",
        "  rangeValue?: number;",
        "}",
        "",
        "/** An action requested through assistive technology. */",
        "interface AccessibilityAction {",
        "  readonly id: string;",
        "  readonly action: \"press\" | \"focus\" | \"increment\" | \"decrement\" | \"setValue\";",
        "  /** New text for setValue. */",
        "  readonly value: string;",
        "}",
        "",
        "/** System preferences reported by sys.device.getPreferences(). */",
        "interface DevicePreferences {",
        "  /** The system uses a dark appearance. */",
        "  readonly darkMode: boolean;",
        "  /** The user asked for less motion. */",
        "  readonly reducedMotion: boolean;",
        "  /** The user asked for more contrast. */",
        "  readonly highContrast: boolean;",
        "  /** Text size multiplier chosen by the user (1 = default). */",
        "  readonly fontScale: number;",
        "  /** Insets, in physical pixels, to keep free of content (notches, system bars). */",
        "  readonly safeArea: { readonly top: number; readonly right: number; readonly bottom: number; readonly left: number };",
        "  /** Height, in physical pixels from the bottom, covered by the on-screen keyboard; 0 when hidden or on desktop. */",
        "  readonly keyboardInset: number;",
        "}",
        "",
    ]
    for subsystem in PILOT_SUBSYSTEMS:
        contract = contracts[subsystem]
        typescript = contract.get("typescript")
        if not isinstance(typescript, dict):
            raise ValueError(f"{subsystem}: missing typescript metadata")
        interface = typescript.get("interface")
        kind = typescript.get("kind")
        description = typescript.get("description")
        if not all(isinstance(value, str) and value for value in
                   (interface, kind, description)):
            raise ValueError(f"{subsystem}: incomplete typescript metadata")
        lines.extend([f"/** {description} */", f"interface {interface} {{"])
        for operation in contract.get("operations", []):
            name = javascript_export(operation)
            operation_description = operation.get("typescript_description")
            if operation_description:
                lines.append(f"  /** {operation_description} */")
            if kind == "capability_entries":
                lines.append(f"  readonly {name}: CapabilityEntry;")
            elif kind == "methods":
                parameters, result = parse_signature(operation.get("signature"))
                rendered = ", ".join(f"{param}: {type_name}"
                                     for param, type_name in parameters)
                lines.append(f"  {name}({rendered}): {result};")
            else:
                raise ValueError(f"{subsystem}: unsupported TypeScript kind: {kind}")
        lines.extend(["}", ""])
    return "\n".join(lines)


def render_support_markdown(matrix):
    lines = [
        "# Managed API Support Matrix",
        "",
        "Generated by `scripts/generate-contract-artifacts.py` from `api/contracts/`.",
        "Do not edit manually.",
        "",
        "| Subsystem | Operations | JavaScript | Lua | Wasmtime | Browser WASM |",
        "|---|---:|---|---|---|---|",
    ]
    for subsystem, summary in sorted(matrix["subsystems"].items()):
        cells = []
        for runtime in ("javascript", "lua", "wasmtime", "browser_wasm"):
            value = summary["runtimes"].get(runtime)
            if value:
                platforms = ", ".join(value["platforms"])
                cells.append(f"{platforms} ({value['exportCount']})")
            else:
                unsupported = summary["unsupportedRuntimes"].get(runtime)
                cells.append("unsupported" if unsupported else "-")
        lines.append(
            f"| `{subsystem}` | {summary['operationCount']} | " +
            " | ".join(cells) + " |"
        )
    lines.extend([
        "",
        "Numbers in parentheses are guest-visible exports. Runtime-specific omissions",
        "and ownership/error metadata are available in `api/support-matrix.json`.",
        "",
    ])
    return "\n".join(lines)


def export_names(contract, runtime, exported):
    values = exported if isinstance(exported, list) else [exported]
    default_namespace = contract.get("runtimes", {}).get(runtime, {}).get("namespace")
    names = []
    for value in values:
        if isinstance(value, str):
            name = value
            namespace = default_namespace
        elif isinstance(value, dict):
            name = value.get("name")
            namespace = value.get("namespace", default_namespace)
        else:
            name = None
            namespace = None
        if not name:
            raise ValueError(
                f"{contract['subsystem']}: invalid {runtime} operation export")
        if isinstance(namespace, str):
            name = f"{namespace}.{name}"
        names.append(name)
    return names


def render_operation_availability(contracts):
    lines = [
        API_AVAILABILITY_START,
        "## Runtime availability",
        "",
        "This section is generated from `api/contracts/*.json`. Each cell names the",
        "guest-visible export; `-` means that operation is not exposed to that runtime.",
        "Platform lists describe where each runtime adapter is registered.",
        "",
    ]
    for subsystem, contract in sorted(contracts.items()):
        lines.extend([f"### `{subsystem}`", ""])
        platforms = []
        for runtime, label in RUNTIME_LABELS.items():
            details = contract.get("runtimes", {}).get(runtime)
            if details:
                values = ", ".join(details.get("platforms", []))
                platforms.append(f"**{label}:** {values}")
            elif runtime in contract.get("unsupported_runtimes", {}):
                platforms.append(f"**{label}:** unsupported")
        lines.extend(["; ".join(platforms) + ".", ""])
        lines.extend([
            '<div class="api-availability-table">',
            "<table>",
            "<thead><tr><th>Operation</th><th>Signature</th>"
            "<th>JavaScript</th><th>Lua</th><th>Wasmtime</th>"
            "<th>Browser WASM</th></tr></thead>",
            "<tbody>",
        ])
        for operation in contract.get("operations", []):
            cells = [operation["name"], operation.get("signature", "-")]
            exports = operation.get("exports", {})
            for runtime in RUNTIME_LABELS:
                exported = exports.get(runtime)
                names = export_names(contract, runtime, exported) if exported else []
                cells.append("<br>".join(
                    f"<code>{html.escape(name)}</code>" for name in names) or "-")
            rendered = []
            for index, cell in enumerate(cells):
                value = cell if index >= 2 else html.escape(str(cell))
                if index == 0:
                    value = f"<code>{value}</code>"
                rendered.append(f"<td>{value}</td>")
            lines.append("<tr>" + "".join(rendered) + "</tr>")
        lines.extend(["</tbody>", "</table>", "</div>", ""])
    lines.extend([API_AVAILABILITY_END, ""])
    return "\n".join(lines)


def render_api_reference(root, contracts):
    path = root / "documentation" / "pages" / "api-reference.md"
    content = path.read_text(encoding="utf-8")
    if API_AVAILABILITY_START not in content or API_AVAILABILITY_END not in content:
        raise ValueError("api-reference.md is missing generated availability markers")
    before, remainder = content.split(API_AVAILABILITY_START, 1)
    _, after = remainder.split(API_AVAILABILITY_END, 1)
    return before + render_operation_availability(contracts) + after.lstrip("\n")


def render_registration_manifest(contracts):
    registrations = []
    for subsystem, contract in sorted(contracts.items()):
        for runtime, details in sorted(contract.get("runtimes", {}).items()):
            registrations.append({
                "subsystem": subsystem,
                "runtime": runtime,
                "symbol": details["registration_symbol"],
                "source": details["source"],
                "namespace": details["namespace"],
                "platforms": details["platforms"],
            })
    return json.dumps({"version": 1, "registrations": registrations},
                      indent=2, sort_keys=True) + "\n"


def render_conformance_vectors(root, contracts):
    matrix = json.loads(
        (root / "api" / "conformance-matrix.json").read_text(encoding="utf-8"))
    vectors = []
    for subsystem, details in sorted(matrix.get("subsystems", {}).items()):
        if details.get("mode") != "normalized_trace":
            continue
        contract = contracts[subsystem]
        for operation in contract.get("operations", []):
            exports = {}
            for runtime in details["runtimes"]:
                exported = operation.get("exports", {}).get(runtime)
                if exported is not None:
                    values = exported if isinstance(exported, list) else [exported]
                    exports[runtime] = [
                        value if isinstance(value, str) else value.get("name")
                        for value in values
                    ]
            vectors.append({
                "subsystem": subsystem,
                "operation": operation["name"],
                "signature": operation["signature"],
                "exports": exports,
                "runtimes": details["runtimes"],
                "test": details["test"],
            })
    return json.dumps({"version": 1, "vectors": vectors},
                      indent=2, sort_keys=True) + "\n"


def update_or_check(path, content, check, stale):
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == content:
        return
    if check:
        stale.append(path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path,
                        default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.repo.resolve()
    contracts = load_contracts(root)
    missing = [name for name in PILOT_SUBSYSTEMS if name not in contracts]
    if missing:
        print(f"missing pilot contracts: {', '.join(missing)}", file=sys.stderr)
        return 1
    try:
        matrix = build_support_matrix(root, contracts)
        outputs = {
            root / "scripts" / "type-fragments" / "generated-basics.d.ts.frag":
                render_types(contracts),
            root / "api" / "support-matrix.json":
                json.dumps(matrix, indent=2, sort_keys=True) + "\n",
            root / "api" / "SUPPORT.md": render_support_markdown(matrix),
            root / "documentation" / "pages" / "api-reference.md":
                render_api_reference(root, contracts),
            root / "api" / "generated" / "registration-manifest.json":
                render_registration_manifest(contracts),
            root / "api" / "generated" / "conformance-vectors.json":
                render_conformance_vectors(root, contracts),
        }
    except (KeyError, TypeError, ValueError, json.JSONDecodeError) as error:
        print(f"contract artifact generation failed: {error}", file=sys.stderr)
        return 1

    stale = []
    for path, content in outputs.items():
        update_or_check(path, content, args.check, stale)
    if stale:
        for path in stale:
            print(f"stale generated artifact: {path.relative_to(root)}", file=sys.stderr)
        print("run `make generate-contract-artifacts`", file=sys.stderr)
        return 1
    action = "Verified" if args.check else "Generated"
    print(f"{action} {len(outputs)} contract artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
