#!/usr/bin/env python3
"""Embeds a set of files into a C header as a table of gzip-compressed entries.

Usage: python3 embed_tree.py [--shallower-references] <var_name> <output_file> <dest=source>...

Generates a header with:
  static const EmbeddedTreeFile <var_name>[];   /* {path, data, len, uncompressed_len, is_gzip} */
  static const size_t           <var_name>_count;

--shallower-references drops one "../" from `/// <reference path="../...">`
lines: the files are written one directory closer to budo.d.ts than their
sources are (examples/budo-ui/lib/core.js becomes ui/lib/core.js).
"""

import gzip
import os
import re
import sys

REFERENCE = re.compile(rb'^(/// <reference path=")\.\./', re.MULTILINE)


def transform(data, shallower):
    return REFERENCE.sub(rb"\1", data) if shallower else data


def main():
    args = sys.argv[1:]
    shallower = False
    if args and args[0] == "--shallower-references":
        shallower = True
        args = args[1:]
    if len(args) < 3:
        print(f"Usage: {sys.argv[0]} [--shallower-references] <var_name> <output_file> <dest=source>...",
              file=sys.stderr)
        sys.exit(1)
    var_name, output_file, pairs = args[0], args[1], args[2:]

    lines = [
        "/* Auto-generated by cmake/embed_tree.py -- do not edit. */",
        "#pragma once",
        "#include <stddef.h>",
        "",
        "#ifndef BUDO_EMBEDDED_TREE_FILE",
        "#define BUDO_EMBEDDED_TREE_FILE",
        "typedef struct EmbeddedTreeFile",
        "{",
        "    const char *path;",
        "    const unsigned char *data;",
        "    size_t len;",
        "    size_t uncompressed_len;",
        "    int is_gzip;",
        "} EmbeddedTreeFile;",
        "#endif",
        "",
    ]
    entries = []
    total = 0
    for index, pair in enumerate(sorted(pairs)):
        dest, _, source = pair.partition("=")
        if not dest or not source:
            print(f"Error: expected dest=source, got {pair!r}", file=sys.stderr)
            sys.exit(1)
        with open(source, "rb") as f:
            original = transform(f.read(), shallower)
        data = gzip.compress(original, mtime=0)
        total += len(original)
        name = f"{var_name}_{index}"
        lines.append(f"static const unsigned char {name}[] = {{")
        for i in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
        lines += ["    0x00", "};", ""]
        entries.append(f'    {{"{dest}", {name}, {len(data)}U, {len(original)}U, 1}},')

    lines.append(f"static const EmbeddedTreeFile {var_name}[] = {{")
    lines += entries
    lines += ["};", f"static const size_t {var_name}_count = {len(entries)}U;", ""]

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w") as f:
        f.write("\n".join(lines))
    print(f"Embedded {len(entries)} files -> {output_file} ({total} original bytes as {var_name})")


if __name__ == "__main__":
    main()
