#!/usr/bin/env python3
"""Embeds a binary file into a C header as a zero-terminated byte array.

Usage: python3 embed_file.py [--gzip] <input_file> <var_name> <output_file>

Generates a header with:
  static const unsigned char <var_name>_data[];
  static const size_t        <var_name>_len;
    static const size_t        <var_name>_uncompressed_len;
    static const int           <var_name>_is_gzip;
"""

import sys
import os
import gzip


def main():
    args = sys.argv[1:]
    gzip_payload = False
    if args and args[0] == "--gzip":
        gzip_payload = True
        args = args[1:]

    if len(args) != 3:
        print(
            f"Usage: {sys.argv[0]} [--gzip] <input_file> <var_name> <output_file>",
            file=sys.stderr,
        )
        sys.exit(1)

    input_file = args[0]
    var_name = args[1]
    output_file = args[2]

    with open(input_file, "rb") as f:
        original_data = f.read()

    data = gzip.compress(original_data, mtime=0) if gzip_payload else original_data

    out_lines = [
        "/* Auto-generated by cmake/embed_file.py -- do not edit. */",
        "#pragma once",
        "#include <stddef.h>",
        "",
        f"static const unsigned char {var_name}_data[] = {{",
    ]

    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        out_lines.append(f"    {hex_bytes},")

    out_lines += [
        "    0x00",
        "};",
        "",
        f"static const size_t {var_name}_len = {len(data)}U;",
        f"static const size_t {var_name}_uncompressed_len = {len(original_data)}U;",
        f"static const int {var_name}_is_gzip = {1 if gzip_payload else 0};",
        "",
    ]

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w") as f:
        f.write("\n".join(out_lines))

    suffix = "gzip-compressed " if gzip_payload else ""
    print(
        f"Embedded {input_file} -> {output_file} "
        f"({suffix}{len(data)} bytes, {len(original_data)} original bytes as {var_name})"
    )


if __name__ == "__main__":
    main()
