name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Android pack
        uses: ./.github/actions/android-pack
        with:
          url: ${{ secrets.BUDO_ANDROID_PACK_URL }}

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libsdl2-dev libfreetype6-dev libfontconfig1-dev libssl-dev zlib1g-dev libgl1-mesa-dev

      - name: Skia
        uses: ./.github/actions/skia

      - name: Download ONNX
        run: ./scripts/setup-onnx.sh

      - name: Download STB
        run: ./scripts/setup-stb.sh

      - name: Build
        run: make build CMAKE_FLAGS="-DBUDO_GITHUB_REPOSITORY_OVERRIDE=${{ github.repository }}"

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Android pack
        uses: ./.github/actions/android-pack
        with:
          url: ${{ secrets.BUDO_ANDROID_PACK_URL }}

      - name: Install packages
        run: brew install cmake sdl2

      - name: Skia
        uses: ./.github/actions/skia

      - name: Download ONNX
        run: ./scripts/setup-onnx.sh

      - name: Download STB
        run: ./scripts/setup-stb.sh

      - name: Build
        run: make build CMAKE_FLAGS="-DBUDO_GITHUB_REPOSITORY_OVERRIDE=${{ github.repository }}"

  build-windows:
    uses: ./.github/workflows/windows-build.yml
