name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get install cmake build-essential libsdl2-dev libfreetype6-dev libfontconfig1-dev

      - name: Download Skia
        run: ./scripts/setup-skia.sh

      - name: Download ONNX
        run: ./scripts/setup-onnx.sh

      - name: Download STB
        run: ./scripts/setup-stb.sh

      - name: Build
        run: make build
